### ISSUE TITLE
loading fribidi library issue on linux

### ISSUE THREAD

**Issue by fomarkh** [Ghasan/FriBidiSharp#1]
After installing libfribidi-bin. the application displays this error:
An unhandled exception has occurred while executing the request.
      System.DllNotFoundException: Unable to load shared library 'fribidi' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libfribidi: cannot open shared object file: No such file or directory
         at FriBidiSharp.FriBidiSharpMain.__Internal.Log2vis(UInt32[] str, Int32 len, UInt32[] pbase_dir, UInt32[] visual_str, Int32[] positions_L_to_V, Int32[] positions_V_to_L, SByte[] embedding_levels)

**Comment by Ghasan** [comment]
Hi,

You will need to install libfribidi as the following (on Ubuntu):
`apt-get install -y libfribidi0`

You might also need to create a symbolic link to it:
`ln -s /usr/lib/x86_64-linux-gnu/libfribidi.so.0 /usr/lib/x86_64-linux-gnu/libfribidi.so`

Regards,
Ghasan

**Comment by fomarkh** [comment]
Hi Ghasan,
Many thanks, it's working now

Regards
